#!/usr/bin/env bash

set -euo pipefail
cd "$(dirname "$0")/../.."
shopt -s extglob

script/bundle-linux --flatpak
archive_match="tau(-[a-zA-Z0-9]+)?-linux-$(uname -m)\.tar\.gz"
archive=$(ls "target/release" | grep -E ${archive_match})
channel=$(<crates/tau/RELEASE_CHANNEL)

export CHANNEL="$channel"
export ARCHIVE="$archive"
if [[ "$channel" == "dev" ]]; then
    export APP_ID="ai.tau.TAUDev"
    export APP_NAME="TAU Dev"
    export BRANDING_LIGHT="#99c1f1"
    export BRANDING_DARK="#1a5fb4"
    export ICON_FILE="tau-icon"
elif [[ "$channel" == "nightly" ]]; then
    export APP_ID="ai.tau.TAUNightly"
    export APP_NAME="TAU Nightly"
    export BRANDING_LIGHT="#e9aa6a"
    export BRANDING_DARK="#1a5fb4"
    export ICON_FILE="tau-icon"
elif [[ "$channel" == "preview" ]]; then
    export APP_ID="ai.tau.TAUPreview"
    export APP_NAME="TAU Preview"
    export BRANDING_LIGHT="#99c1f1"
    export BRANDING_DARK="#1a5fb4"
    export ICON_FILE="tau-icon"
elif [[ "$channel" == "stable" ]]; then
    export APP_ID="ai.tau.TAU"
    export APP_NAME="TAU"
    export BRANDING_LIGHT="#99c1f1"
    export BRANDING_DARK="#1a5fb4"
    export ICON_FILE="tau-icon"
else
    echo "Invalid channel: '$channel'"
    exit
fi

envsubst < "crates/tau/resources/flatpak/manifest-template.json" > "$APP_ID.json"
flatpak-builder --user --install --force-clean build "$APP_ID.json"
flatpak build-bundle ~/.local/share/flatpak/repo "target/release/$APP_ID.flatpak" "$APP_ID"
echo "Created 'target/release/$APP_ID.flatpak'"
