#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs TAU onto your system into ~/.local, making it available as ~/.local/bin/TAU.

  Before running this you should ensure you have all the build dependencies installed with `./script/linux`.
  "
  exit 1
fi
export TAU_CHANNEL=$(<crates/tau/RELEASE_CHANNEL)
export TAU_UPDATE_EXPLANATION="You need to fetch and rebuild TAU in $(pwd)"
script/bundle-linux

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="tau-${arch}-linux.tar.xz"
export TAU_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh
